services:
  db:
    image: postgres:15-alpine
    container_name: owl_backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: owl_tf_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data,
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d owl_tf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: owl_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/owl_tf_db
    command: node index.js
    depends_on:
      db:
        condition: service_healthy # This forces the API to wait for the pulse!

  frontend:
    build: ./frontend
    container_name: owl_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "0.0.0.0:5173:5173" # Explicitly bind to all network interfaces
    # connection stuff
    # environment: 
    #   - VITE_API_URL=http://10.0.0.203:5000 # Your Mac's IP

volumes:
  pgdata: